#!/bin/bash

# Text color
SETCOLOR_RED="echo \\033[1;31m"
SETCOLOR_GREEN="echo \\033[1;32m"
SETCOLOR_BLUE="echo \\033[1;34m"
SETCOLOR_YELLOW="echo \\033[1;33m"
SETCOLOR_MAGENTA="echo \\033[1;35m"
SETCOLOR_CYAN="echo \\033[1;36m"
SETCOLOR_WHITE="echo \\033[1;37m"
SETCOLOR_GRAY="echo \\033[1;30m"
SETCOLOR_NORMAL="echo \\033[0;39m"

# Text color background
SETCOLOR_WHITE_BLACK="echo \\033[1;40m"
SETCOLOR_WHITE_RED="echo \\033[1;41m"
SETCOLOR_WHITE_GREEN="echo \\033[1;42m"
SETCOLOR_WHITE_BROWN="echo \\033[1;43m"
SETCOLOR_WHITE_BLUE="echo \\033[1;44m"
SETCOLOR_WHITE_MAGENTA="echo \\033[1;45m"
SETCOLOR_WHITE_CYAN="echo \\033[1;46m"
SETCOLOR_WHITE_GRAY="echo \\033[1;47m"

sleep 0

${SETCOLOR_RED}
echo "TEXT RED"

${SETCOLOR_GREEN}
echo "TEXT GREEN"

${SETCOLOR_BLUE}
echo "TEXT BLUE"

${SETCOLOR_YELLOW}
echo "TEXT YELLOW"

${SETCOLOR_MAGENTA}
echo "TEXT MAGENTA"

${SETCOLOR_CYAN}
echo "TEXT CYAN"

${SETCOLOR_WHITE}
echo "TEXT WHITE"

${SETCOLOR_GRAY}
echo "TEXT GRAY"

${SETCOLOR_NORMAL}
echo "TEXT NORMAL"

${SETCOLOR_WHITE_BLACK}
echo "TEXT WHITE BACKGROUND BLACK"

${SETCOLOR_WHITE_RED}
echo "TEXT WHITE BACKGROUND RED"

${SETCOLOR_WHITE_GREEN}
echo "TEXT WHITE BACKGROUND GREEN"

${SETCOLOR_WHITE_BROWN}
echo "TEXT WHITE BACKGROUND BROWN"

${SETCOLOR_WHITE_BLUE}
echo "TEXT WHITE BACKGROUND BLUE"

${SETCOLOR_WHITE_MAGENTA}
echo "TEXT WHITE BACKGROUND MAGENTA"

${SETCOLOR_WHITE_CYAN}
echo "TEXT WHITE BACKGROUND CYAN"

${SETCOLOR_WHITE_GRAY}
echo "TEXT WHITE BACKGROUND GRAY"
